files = [
    'stream/taysuwuclothpack_male_p.rpf/*',
    'stream/taysuwuclothpack_male.rpf/*',
    'stream/taysuwuclothpack_female_p.rpf/*',
    'stream/taysuwuclothpack_female.rpf/*',
    'stream/creaturemetadata.rpf/*'
]

[meta]
'stream/mp_m_freemode_01_mp_m_taysuwuclothpack.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/mp_f_freemode_01_mp_f_taysuwuclothpack.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/pedalternatevariations.meta' = 'ALTERNATE_VARIATIONS_FILE'